let parent = document.querySelector(".content");

export default function generateMenu() {
  removeAllChildNodes(parent);
  let background = document.createElement("div");
  background.id = "background";
  let page = document.createElement("div");
  page.className = "page";

  let header = document.createElement("div");
  header.id = "header";

  //   Header Start
  let nav1 = document.createElement("ul");
  nav1.className = "navigation";
  let aboutList = document.createElement("li");
  let aboutLink = document.createElement("a");
  aboutLink.className = "about-btn";
  aboutLink.classList.add("active");
  aboutLink.innerText = "ABOUT";
  aboutList.appendChild(aboutLink);
  nav1.appendChild(aboutList);
  header.appendChild(nav1);

  let logo = document.createElement("a");
  logo.href = "https://www.youtube.com/watch?v=RE4usAXuVKo&t=196s";
  logo.id = "logo";
  //   logo.target = "_blank";
  let logoImg = document.createElement("img");
  logoImg.src = "/src/resource/logo2.jpg";
  logoImg.style.width = "276px";
  logoImg.style.height = "203px";
  logo.appendChild(logoImg);
  header.appendChild(logo);

  let nav2 = document.createElement("ul");
  nav2.id = "navigation";
  let menuList = document.createElement("li");
  let menuLink = document.createElement("a");
  menuLink.className = "menu-btn";
  menuLink.innerText = "OUR MENU";
  menuList.appendChild(menuLink);
  nav2.appendChild(menuList);

  let contactList = document.createElement("li");
  let contactLink = document.createElement("a");
  contactLink.className = "contact-btn";
  contactLink.innerText = "CONTACT US";
  contactList.appendChild(contactLink);
  nav2.appendChild(contactList);
  header.appendChild(nav2);
  //   Header End
  let body1 = document.createElement("div");
  body1.id = "body";
  let content = document.createElement("div");
  content.className = "content";
  let body2 = document.createElement("div");
  body2.className = "body";
  let h3 = document.createElement("h3");
  h3.innerText = "ABOUT";
  body2.appendChild(h3);
  // Section Start
  let section = document.createElement("ul");
  section.className = "section";
  // Section End
  let ul1 = document.createElement("ul");
  let li1_1 = document.createElement("li");
  let h4 = document.createElement("h4");
  h4.innerText = "This website as a whole is generated by JavaScript only.";
  let p = document.createElement("p");
  p.innerText =
    " You could argue that some of the greatest software developers back in the ninties would have never thought this was possible, but in the grand scheme of things is this really that impressive nowadays?";
  li1_1.appendChild(h4);
  li1_1.appendChild(p);
  ul1.appendChild(li1_1);
  let ul2 = document.createElement("ul");
  ul2.className = "news";
  appendToUL(ul2, "Lorem ipsum dolor sit amet, consectetur adipiscing.");
  appendToUL(ul2, "Nam sit amet dui gravida tellus lobortis ullamcorper.");
  appendToUL(ul2, "Sed sit amet interdum magna vulputate mollis lectus.");
  appendToUL(ul2, "Vestibulum in feugiat dolor. Pellentesque in adipiscing.");
  appendToUL(ul2, "Maecenas eu ipsum a odio varius mollis vitae at ante.");
  appendToUL(ul2, "Aenean faucibus suscipit velit at tincidunt.");
  appendToUL(ul2, "Mauris pharetra sem quis convallis gravida enim.");

  body2.appendChild(h3);
  body2.appendChild(ul1);
  body2.appendChild(ul2);
  content.appendChild(body2);
  body1.appendChild(content);
  page.appendChild(header);
  page.appendChild(body1);
  background.appendChild(page);
  parent.appendChild(background);
}

function appendToUL(ul, li) {
  let currentList = document.createElement("li");
  currentList.innerText = li;
  ul.appendChild(currentList);
}
function removeAllChildNodes(parent) {
  while (parent.firstChild) {
    parent.removeChild(parent.firstChild);
  }
}
